/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.LuongBUS;
import DAL.LuongDAL;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DTO.Luong;
import com.sun.org.apache.xerces.internal.impl.dv.DatatypeValidator;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Statement;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Ngoc
 */
public class frmLuong extends javax.swing.JPanel {
    
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    DefaultTableModel modelLuong;
    DefaultTableModel modelTangLuong;
    
    private Connection conn;
    /**
     * Creates new form frmLuong
     */
    public frmLuong() {
        initComponents();
        
        //LuongBUS.getCBboxMaNV(cbxMaNhanVien);
        loadcbxMaNhanVien();
        //showBL();
        showL();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        //modelLuong = (DefaultTableModel)tblLuong.getModel();
        modelLuong = (DefaultTableModel)tblLuong.getModel();
        
    }  
    public void loadcbxMaNhanVien(){
        Connection ketNoi = KetNoiSQL.layKetnoi();
        String sql = "SELECT MaNV FROM TblTTNVCoBan "+
"               WHERE MaNV IN ( SELECT MaNV \n" +
"		FROM TblTTNVCoBan\n" +
"               EXCEPT\n" +
"               SELECT MaNV\n" +
"		FROM TblLuong\n" +
"		)";
        try{
            Statement state = ketNoi.createStatement();
            ResultSet rs = state.executeQuery(sql);
            while(rs.next()){
                cbxMaNhanVien.addItem(rs.getString("MANV"));   
            }
        }
        catch(Exception e){
            System.out.println("Khong load duoc comboBox");
        }
    }
//    public void showBL() {
//        ArrayList<BangLuongCongTy> bl = BangLuongCongTyDAL.blList();
//        DefaultTableModel model = (DefaultTableModel)tblLuong.getModel();
//        Object[] row = new Object[17];
//        for (int i=0;i<bl.size();i++) {
//            row[0]=bl.get(i).getMaLuong();
//            row[1]=bl.get(i).getChucVu();
//            row[2]=bl.get(i).getChucDanh();
//            row[3]=bl.get(i).getLuongCoBan();
//            row[4]=bl.get(i).getPhuCapChucVu();
//            row[5]=bl.get(i).getNgayNhap();
//            row[6]=bl.get(i).getLuongCoBanMoi();
//            row[7]=bl.get(i).getNgaySua();
//            row[8]=bl.get(i).getLyDo();
//            row[9]=bl.get(i).getPhuCapCVuMoi();
//            row[10]=bl.get(i).getNgaySua();
//            row[11]=bl.get(i).getGhiChu();
//            model.addRow(row);
//        };
//    }
    
    public void showL() {
        ArrayList<Luong> l = LuongDAL.tlList();
        DefaultTableModel model = (DefaultTableModel)tblLuong.getModel();
        Object[] row = new Object[17];
        for (int i=0;i<l.size();i++) {
            row[0]=l.get(i).getMaNhanVien();
            row[1]=l.get(i).getMaLuong();
            row[2]=l.get(i).getHoTen();
            row[3]=l.get(i).getGioiTinh();
            row[4]=l.get(i).getChucVu();
            row[5]=l.get(i).getChucDanh();
            row[6]=l.get(i).getLuongCoBan();
            row[7]=l.get(i).getLuongCoBan_gio();
            row[8]=l.get(i).getPhuCapCV();
            row[9]=l.get(i).getHinhThuc();
            row[10]=l.get(i).getNgayNhap();
            row[11]=l.get(i).getGhiChu();
            model.addRow(row);
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnLuong = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblHeader3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        lblHeader7 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblLuong = new javax.swing.JTable();
        lblMaNhanVien = new javax.swing.JLabel();
        cbxMaNhanVien = new javax.swing.JComboBox<>();
        lblMaLuong1 = new javax.swing.JLabel();
        txtMaLuong = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblPCCVMoi_1 = new javax.swing.JLabel();
        lblChucDanh_1 = new javax.swing.JLabel();
        txtChucDanh = new javax.swing.JTextField();
        lblChucVu_1 = new javax.swing.JLabel();
        lblNgayTang = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblLuongCBMoi_1 = new javax.swing.JLabel();
        txtLuongCB_gio = new javax.swing.JTextField();
        lblLuongCBCu = new javax.swing.JLabel();
        txtLuongCB = new javax.swing.JTextField();
        lblLyDo_1 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        lblPCCVCu = new javax.swing.JLabel();
        txtPCCV = new javax.swing.JTextField();
        txtNgayNhap = new com.toedter.calendar.JDateChooser();
        cbxChucVu = new javax.swing.JComboBox<>();
        cbxGioiTinh = new javax.swing.JComboBox<>();
        cbxHinhThuc = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(107, 195, 196));

        jPanel4.setBackground(new java.awt.Color(107, 195, 196));

        pnLuong.setBackground(new java.awt.Color(254, 255, 250));
        pnLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(107, 195, 196)));
        pnLuong.setEnabled(false);

        jPanel9.setBackground(new java.awt.Color(3, 100, 117));

        lblHeader3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblHeader3.setForeground(new java.awt.Color(254, 255, 250));
        lblHeader3.setText("Thông tin về lương nhân viên");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblHeader3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(254, 255, 250));
        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(107, 195, 196)));

        jPanel16.setBackground(new java.awt.Color(3, 100, 117));

        lblHeader7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblHeader7.setForeground(new java.awt.Color(254, 255, 250));
        lblHeader7.setText("Chức năng");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblHeader7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        btnThem.setBackground(new java.awt.Color(3, 100, 117));
        btnThem.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(107, 195, 196));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlnstl/src/add-group.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.setEnabled(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(3, 100, 117));
        btnSua.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(107, 195, 196));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlnstl/src/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.setEnabled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(3, 100, 117));
        btnXoa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(107, 195, 196));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlnstl/src/remove-user.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.setBorder(null);
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setBackground(new java.awt.Color(3, 100, 117));
        btnMoi.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(107, 195, 196));
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlnstl/src/add-group.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.setBorder(null);
        btnMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnXuat.setBackground(new java.awt.Color(3, 100, 117));
        btnXuat.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnXuat.setForeground(new java.awt.Color(107, 195, 196));
        btnXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlnstl/src/document.png"))); // NOI18N
        btnXuat.setBorder(null);
        btnXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSeparator3.setBackground(new java.awt.Color(3, 100, 117));
        jSeparator3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));

        tblLuong.setBackground(new java.awt.Color(254, 255, 250));
        tblLuong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblLuong.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tblLuong.setForeground(new java.awt.Color(3, 100, 117));
        tblLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Mã Lương", "Họ tên", "Giới tính", "Chức vụ", "Chức danh", "Lương CB ", "Lương CB(giờ)", "PCCV ", "Hình thức", "Ngày nhập", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLuong.setGridColor(new java.awt.Color(3, 100, 117));
        tblLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLuongMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblLuong);

        lblMaNhanVien.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMaNhanVien.setForeground(new java.awt.Color(3, 100, 117));
        lblMaNhanVien.setText("Mã nhân viên");

        cbxMaNhanVien.setBackground(new java.awt.Color(107, 195, 196));
        cbxMaNhanVien.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxMaNhanVien.setForeground(new java.awt.Color(3, 100, 117));
        cbxMaNhanVien.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));

        lblMaLuong1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMaLuong1.setForeground(new java.awt.Color(3, 100, 117));
        lblMaLuong1.setText("Mã lương");

        txtMaLuong.setEditable(false);
        txtMaLuong.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtMaLuong.setForeground(new java.awt.Color(3, 100, 117));
        txtMaLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtMaLuong.setEnabled(false);
        txtMaLuong.setMinimumSize(new java.awt.Dimension(3, 26));
        txtMaLuong.setPreferredSize(new java.awt.Dimension(36, 28));

        lblHoTen.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(3, 100, 117));
        lblHoTen.setText("Họ tên*");

        txtHoTen.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtHoTen.setForeground(new java.awt.Color(3, 100, 117));
        txtHoTen.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtHoTen.setEnabled(false);
        txtHoTen.setMinimumSize(new java.awt.Dimension(3, 26));
        txtHoTen.setPreferredSize(new java.awt.Dimension(36, 28));

        lblPCCVMoi_1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblPCCVMoi_1.setForeground(new java.awt.Color(3, 100, 117));
        lblPCCVMoi_1.setText("Hình thức *");

        lblChucDanh_1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblChucDanh_1.setForeground(new java.awt.Color(3, 100, 117));
        lblChucDanh_1.setText("Chức danh*");

        txtChucDanh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtChucDanh.setForeground(new java.awt.Color(3, 100, 117));
        txtChucDanh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtChucDanh.setEnabled(false);
        txtChucDanh.setMinimumSize(new java.awt.Dimension(3, 26));
        txtChucDanh.setPreferredSize(new java.awt.Dimension(36, 28));

        lblChucVu_1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblChucVu_1.setForeground(new java.awt.Color(3, 100, 117));
        lblChucVu_1.setText("Chức vụ*");

        lblNgayTang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNgayTang.setForeground(new java.awt.Color(3, 100, 117));
        lblNgayTang.setText("Ngày nhập");

        lblGioiTinh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(3, 100, 117));
        lblGioiTinh.setText("Giới tính");

        lblLuongCBMoi_1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblLuongCBMoi_1.setForeground(new java.awt.Color(3, 100, 117));
        lblLuongCBMoi_1.setText("Lương (giờ) *");

        txtLuongCB_gio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtLuongCB_gio.setForeground(new java.awt.Color(3, 100, 117));
        txtLuongCB_gio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtLuongCB_gio.setEnabled(false);
        txtLuongCB_gio.setMinimumSize(new java.awt.Dimension(3, 26));
        txtLuongCB_gio.setPreferredSize(new java.awt.Dimension(36, 28));
        txtLuongCB_gio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLuongCB_gioKeyPressed(evt);
            }
        });

        lblLuongCBCu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblLuongCBCu.setForeground(new java.awt.Color(3, 100, 117));
        lblLuongCBCu.setText("Lương CB*");

        txtLuongCB.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtLuongCB.setForeground(new java.awt.Color(3, 100, 117));
        txtLuongCB.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtLuongCB.setEnabled(false);
        txtLuongCB.setMinimumSize(new java.awt.Dimension(3, 26));
        txtLuongCB.setPreferredSize(new java.awt.Dimension(36, 28));
        txtLuongCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLuongCBKeyPressed(evt);
            }
        });

        lblLyDo_1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblLyDo_1.setForeground(new java.awt.Color(3, 100, 117));
        lblLyDo_1.setText("Ghi chú");

        txtGhiChu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(3, 100, 117));
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtGhiChu.setEnabled(false);
        txtGhiChu.setMinimumSize(new java.awt.Dimension(3, 26));
        txtGhiChu.setPreferredSize(new java.awt.Dimension(36, 28));

        lblPCCVCu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblPCCVCu.setForeground(new java.awt.Color(3, 100, 117));
        lblPCCVCu.setText("PC CV *");

        txtPCCV.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPCCV.setForeground(new java.awt.Color(3, 100, 117));
        txtPCCV.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtPCCV.setEnabled(false);
        txtPCCV.setMinimumSize(new java.awt.Dimension(3, 26));
        txtPCCV.setPreferredSize(new java.awt.Dimension(36, 28));
        txtPCCV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPCCVKeyPressed(evt);
            }
        });

        txtNgayNhap.setForeground(new java.awt.Color(3, 100, 117));
        txtNgayNhap.setDate(new java.util.Date(1561799207000L));
        txtNgayNhap.setDateFormatString("yyyy-MM-dd");
        txtNgayNhap.setEnabled(false);
        txtNgayNhap.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        cbxChucVu.setBackground(new java.awt.Color(107, 195, 196));
        cbxChucVu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxChucVu.setForeground(new java.awt.Color(3, 100, 117));
        cbxChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Director", "Manager", "Employee" }));
        cbxChucVu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        cbxChucVu.setEnabled(false);

        cbxGioiTinh.setBackground(new java.awt.Color(107, 195, 196));
        cbxGioiTinh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxGioiTinh.setForeground(new java.awt.Color(3, 100, 117));
        cbxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbxGioiTinh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        cbxGioiTinh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbxGioiTinh.setEnabled(false);

        cbxHinhThuc.setBackground(new java.awt.Color(107, 195, 196));
        cbxHinhThuc.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxHinhThuc.setForeground(new java.awt.Color(3, 100, 117));
        cbxHinhThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Part time", "Full time" }));
        cbxHinhThuc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        cbxHinhThuc.setEnabled(false);
        cbxHinhThuc.setMinimumSize(new java.awt.Dimension(61, 26));
        cbxHinhThuc.setName(""); // NOI18N

        javax.swing.GroupLayout pnLuongLayout = new javax.swing.GroupLayout(pnLuong);
        pnLuong.setLayout(pnLuongLayout);
        pnLuongLayout.setHorizontalGroup(
            pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane7)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLuongLayout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addContainerGap(890, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLuongLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnLuongLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(lblHoTen)
                            .addGap(49, 49, 49)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLuongLayout.createSequentialGroup()
                            .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnLuongLayout.createSequentialGroup()
                                    .addComponent(lblMaNhanVien)
                                    .addGap(31, 31, 31))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLuongLayout.createSequentialGroup()
                                    .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblChucDanh_1)
                                        .addComponent(lblMaLuong1))
                                    .addGap(38, 38, 38)))
                            .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtChucDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxMaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtMaLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGioiTinh)
                    .addComponent(lblPCCVMoi_1)
                    .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNgayTang)
                        .addComponent(lblPCCVCu)))
                .addGap(18, 18, 18)
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPCCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnLuongLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnLuongLayout.createSequentialGroup()
                                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnLuongLayout.createSequentialGroup()
                                        .addComponent(lblLuongCBCu)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLuongLayout.createSequentialGroup()
                                        .addComponent(lblLuongCBMoi_1)
                                        .addGap(18, 18, 18)))
                                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLuongCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLuongCB_gio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnLuongLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblLyDo_1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnLuongLayout.createSequentialGroup()
                        .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnLuongLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnLuongLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblChucVu_1)
                                .addGap(34, 34, 34)
                                .addComponent(cbxChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)))
                .addGap(55, 55, 55))
        );
        pnLuongLayout.setVerticalGroup(
            pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLuongLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnLuongLayout.createSequentialGroup()
                        .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGioiTinh)
                            .addComponent(lblMaNhanVien))
                        .addGap(18, 18, 18)
                        .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaLuong1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgayTang, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(pnLuongLayout.createSequentialGroup()
                        .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLuongCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLuongCBCu)
                            .addComponent(cbxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLuongCB_gio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLuongCBMoi_1))))
                .addGap(18, 18, 18)
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChucDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPCCVCu)
                        .addComponent(lblChucDanh_1))
                    .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPCCV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblChucVu_1))
                    .addComponent(cbxChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPCCVMoi_1)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHoTen))
                    .addComponent(lblLyDo_1)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lương Nhân Viên", pnLuong);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPCCVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCCVKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) txtPCCV.setEditable(false);
        else txtPCCV.setEditable(true);
    }//GEN-LAST:event_txtPCCVKeyPressed

    private void txtLuongCBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuongCBKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) txtLuongCB.setEditable(false);
        else txtLuongCB.setEditable(true);
    }//GEN-LAST:event_txtLuongCBKeyPressed

    private void txtLuongCB_gioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuongCB_gioKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) txtLuongCB_gio.setEditable(false);
        else txtLuongCB_gio.setEditable(true);
    }//GEN-LAST:event_txtLuongCB_gioKeyPressed
    
    private void tblLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLuongMouseClicked
        // TODO add your handling code here:
        cbxMaNhanVien.removeAllItems();
        LuongBUS.getCBboxMaNVTb(cbxMaNhanVien);
        
        txtMaLuong.setEnabled(true);
        txtHoTen.setEnabled(true);
        cbxGioiTinh.setEnabled(true);
        cbxChucVu.setEnabled(true);
        txtChucDanh.setEnabled(true);
        txtLuongCB.setEnabled(true);
        txtLuongCB_gio.setEnabled(true);
        txtPCCV.setEnabled(true);
        cbxHinhThuc.setEnabled(true);
        txtNgayNhap.setEnabled(true);
        txtGhiChu.setEnabled(true);
        btnThem.setEnabled(true);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);

        int i = tblLuong.getSelectedRow();
        cbxMaNhanVien.setSelectedItem(modelLuong.getValueAt(i, 0).toString());
        txtMaLuong.setText(modelLuong.getValueAt(i, 1).toString());
        txtHoTen.setText(modelLuong.getValueAt(i, 2).toString());
        cbxGioiTinh.setSelectedItem(modelLuong.getValueAt(i, 3).toString());
        cbxChucVu.setSelectedItem(modelLuong.getValueAt(i, 4).toString());
        txtChucDanh.setText(modelLuong.getValueAt(i, 5).toString());
        txtLuongCB.setText(modelLuong.getValueAt(i, 6).toString());
        txtLuongCB_gio.setText(modelLuong.getValueAt(i, 7).toString());
        txtPCCV.setText(modelLuong.getValueAt(i, 8).toString());
        cbxHinhThuc.setSelectedItem(modelLuong.getValueAt(i, 9).toString());
        txtGhiChu.setText(modelLuong.getValueAt(i, 11).toString());
        try {
            int srow = tblLuong.getSelectedRow();
            Date NgayNhap = new SimpleDateFormat("yyyy-MM-dd").parse((String)modelLuong.getValueAt(srow, 10));
            txtNgayNhap.setDate(NgayNhap);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tblLuongMouseClicked

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
        String link = "D:\\Ex_java\\QLNS-master\\ARCHIVE\\src\\Report\\Luong.jrxml";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=QLNS;" + "username=sa;password=lenhha12345::");
            JasperReport jr = JasperCompileManager.compileReport(link);

            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);

            JasperViewer.viewReport(jp);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnXuatActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
//        cbxMaNhanVien.removeAllItems();
//        LuongBUS.getCBboxMaNV(cbxMaNhanVien);
        
        
        txtHoTen.setEnabled(true);
        cbxGioiTinh.setEnabled(true);
        cbxChucVu.setEnabled(true);
        txtChucDanh.setEnabled(true);
        txtLuongCB.setEnabled(true);
        txtLuongCB_gio.setEnabled(true);
        txtPCCV.setEnabled(true);
        cbxHinhThuc.setEnabled(true);
        txtNgayNhap.setEnabled(true);
        txtGhiChu.setEnabled(true);
        btnThem.setEnabled(true);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(false);
        
        
        LuongBUS.Moi(cbxMaNhanVien, txtMaLuong, txtHoTen, cbxGioiTinh, cbxChucVu, txtChucDanh, txtLuongCB, txtLuongCB_gio, 
                txtPCCV, cbxHinhThuc, txtNgayNhap, txtGhiChu);
        try {
            Connection conn = KetNoiSQL.layKetnoi();
            PreparedStatement ps = conn.prepareStatement("SELECT MANV,HoTen,GioiTinh,ChucVu,ChucDanh FROM dbo.TblTTNVCoBan WHERE MANV="
                    +cbxMaNhanVien.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                    String gioitinh = rs.getString("GioiTinh");
                    int gioitinh_int;
                    if (gioitinh.equals("Nam")) gioitinh_int=0;
                    else gioitinh_int=1;
                    txtChucDanh.setText(rs.getString("ChucDanh"));
                    txtHoTen.setText(rs.getString("HoTen"));
                    cbxGioiTinh.setSelectedIndex(gioitinh_int);
                    
                    String chucvu = rs.getString("ChucVu");
                    int chucvu_int;
                    if (chucvu.equals("Director")) chucvu_int = 0;
                    else if (chucvu.equals("Manager")) chucvu_int = 1;
                    else chucvu_int = 2;
                    cbxChucVu.setSelectedIndex(chucvu_int);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
//        cbxMaNhanVien.setSelectedIndex(0);
//        txtHoTen.setText("");
//        cbxGioiTinh.setSelectedIndex(0);
//        cbxChucVu.setSelectedIndex(0);
//        txtChucDanh.setText("");
//        txtLuongCB.setText("");
//        txtLuongCB_gio.setText("");
//        txtPCCV.setText("");
//        txtHinhThuc.setText("");
//        txtNgayNhap.setDateFormatString("yyyy-MM-dd");
//        txtGhiChu.setText("");
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        
        LuongBUS.Xoa(txtMaLuong.getText());
        DefaultTableModel model = (DefaultTableModel) tblLuong.getModel();
        model.setRowCount(0);
        showL();
        cbxMaNhanVien.removeAllItems();
        loadcbxMaNhanVien();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String NgayNhap = dateFormat.format(txtNgayNhap.getDate());
        LuongBUS.Sua( cbxMaNhanVien.getSelectedItem().toString(), txtHoTen.getText(), cbxGioiTinh.getSelectedItem().toString(), cbxChucVu.getSelectedItem().toString(), txtChucDanh.getText(), txtLuongCB.getText(),
            txtLuongCB_gio.getText(), txtPCCV.getText(), cbxHinhThuc.getSelectedItem().toString(), NgayNhap, txtGhiChu.getText(), txtMaLuong.getText());
        DefaultTableModel model = (DefaultTableModel) tblLuong.getModel();
        model.setRowCount(0);
        showL();
    }//GEN-LAST:event_btnSuaActionPerformed
  
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(txtHoTen.getText().equals("")== true){
            JOptionPane.showMessageDialog(null, "Họ và tên không được để trống!" );
        }else if (txtChucDanh.getText().equals("")==true){
            JOptionPane.showMessageDialog(null, "Chức danh không được để trống!" );
        }else if (txtPCCV.getText().equals("")==true){
            JOptionPane.showMessageDialog(null, "Phụ cấp công việc không được để trống!" );
        }else if (txtGhiChu.getText().equals("")==true){
            JOptionPane.showMessageDialog(null, "Ghi chú không được để trống!" );
        }else if (txtLuongCB_gio.equals("")==true){
                JOptionPane.showMessageDialog(null, "Lương cơ bản (giờ) không được để trống!");
        }else if (txtLuongCB_gio.equals("")==true){
                JOptionPane.showMessageDialog(null, "Lương cơ bản (giờ) không được để trống!");
        }else{
            
            String NgayNhap = dateFormat.format(txtNgayNhap.getDate());
            LuongBUS.Them(cbxMaNhanVien.getSelectedItem().toString(), txtMaLuong.getText(), txtHoTen.getText(), cbxGioiTinh.getSelectedItem().toString(), cbxChucVu.getSelectedItem().toString(), txtChucDanh.getText(), txtLuongCB.getText(),
                txtLuongCB_gio.getText(), txtPCCV.getText(), cbxHinhThuc.getSelectedItem().toString(), NgayNhap, txtGhiChu.getText());
            DefaultTableModel model = (DefaultTableModel) tblLuong.getModel();
            model.setRowCount(0);
            showL();
            cbxMaNhanVien.removeAllItems();
            loadcbxMaNhanVien();
            }
    }//GEN-LAST:event_btnThemActionPerformed
    
    private void cbxMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMaNhanVienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.JComboBox<String> cbxChucVu;
    private javax.swing.JComboBox<String> cbxGioiTinh;
    private javax.swing.JComboBox<String> cbxHinhThuc;
    private javax.swing.JComboBox<String> cbxMaNhanVien;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblChucDanh_1;
    private javax.swing.JLabel lblChucVu_1;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHeader3;
    private javax.swing.JLabel lblHeader7;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblLuongCBCu;
    private javax.swing.JLabel lblLuongCBMoi_1;
    private javax.swing.JLabel lblLyDo_1;
    private javax.swing.JLabel lblMaLuong1;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgayTang;
    private javax.swing.JLabel lblPCCVCu;
    private javax.swing.JLabel lblPCCVMoi_1;
    private javax.swing.JPanel pnLuong;
    private javax.swing.JTable tblLuong;
    private javax.swing.JTextField txtChucDanh;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuongCB;
    private javax.swing.JTextField txtLuongCB_gio;
    private javax.swing.JTextField txtMaLuong;
    private com.toedter.calendar.JDateChooser txtNgayNhap;
    private javax.swing.JTextField txtPCCV;
    // End of variables declaration//GEN-END:variables

}
