    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.ThongTinCaNhanBUS;
import DAL.ThongTinCaNhanDAL;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.TableUI;
import javax.swing.table.DefaultTableModel;
import DTO.ThongTinCaNhan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Ngoc
 */
public class frmThongTinCaNhan extends javax.swing.JPanel{

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    DefaultTableModel model;

    private Connection conn;
    /**
     * Creates new form frmThongTinCaNhan
     */
    public frmThongTinCaNhan() {
        initComponents();
        loadComboBoxMaNV();
        showTTCN();
        ThongTinCaNhanBUS.getCBbox(cbxMaNhanVien);
        //ThongTinCaNhanDAL.loadDtbCbx(cbxMaNhanVien, txtNoiSinh, txtNguyenQuan, txtDiaChiThuongTru, txtDiaChiTamTru, txtSoDienThoai, txtDanToc, txtTonGiao, txtQuocTich, txtTiengNgonNgu, txtTrinhDoNgonNgu, txtHocVan, txtHocHam, txtNgayVaoDoan, txtTenDoanThe, txtChucVuDoan, txtGhiChu);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

        model = (DefaultTableModel) jTable2.getModel();
    }
    
    public void loadComboBoxMaNV(){
        Connection ketNoi = KetNoiSQL.layKetnoi();
        String sql = "SELECT MaNV FROM dbo.TblTTNVCoBan";
        try{
            Statement state = ketNoi.createStatement();
            ResultSet rs = state.executeQuery(sql);
            while(rs.next()){
                cbxMaNhanVien.addItem(rs.getString("MANV"));
            }
        }
        catch(Exception e){
            System.out.println("Khong load duoc comboBox");
        }
    }
    
    public void showTTCN() {
        ArrayList<ThongTinCaNhan> ttcn = ThongTinCaNhanDAL.ttList();
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        Object[] row = new Object[13];
        for (int i=0;i<ttcn.size();i++) {
            row[0]=ttcn.get(i).getMaNhanVien();
            row[1]=ttcn.get(i).gethoTen();
            row[2]=ttcn.get(i).getgioiTinh();
            row[3]=ttcn.get(i).getngaySinh();
            row[4]=ttcn.get(i).getNoiSinh();
            row[5]=ttcn.get(i).getNguyenQuan();
            row[6]=ttcn.get(i).getDiaChiThuongTru();
            row[7]=ttcn.get(i).getDiaChiTamTru();
            row[8]=ttcn.get(i).getSoDienThoai();
            row[9]=ttcn.get(i).getDanToc();
            row[10]=ttcn.get(i).getTonGiao();
            row[11]=ttcn.get(i).getQuocTich();
            row[12]=ttcn.get(i).getGhiChu();
            model.addRow(row);
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        cbxMaNhanVien = new javax.swing.JComboBox<>();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        lblNoiSinh = new javax.swing.JLabel();
        txtNoiSinh = new javax.swing.JTextField();
        lblSoDienThoai = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        lblDanToc = new javax.swing.JLabel();
        txtDanToc = new javax.swing.JTextField();
        lblTonGiao = new javax.swing.JLabel();
        txtTonGiao = new javax.swing.JTextField();
        lblQuocTich = new javax.swing.JLabel();
        txtQuocTich = new javax.swing.JTextField();
        lblDiaChiThuongTru = new javax.swing.JLabel();
        txtDiaChiThuongTru = new javax.swing.JTextField();
        lblDiaChiTamTru = new javax.swing.JLabel();
        txtDiaChiTamTru = new javax.swing.JTextField();
        lblNguyenQuan = new javax.swing.JLabel();
        txtNguyenQuan = new javax.swing.JTextField();
        lblGhiChu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblHeader1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(107, 195, 196));

        jPanel4.setBackground(new java.awt.Color(107, 195, 196));

        jPanel5.setBackground(new java.awt.Color(254, 255, 250));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(107, 195, 196)));

        jPanel6.setBackground(new java.awt.Color(3, 100, 117));

        lblHeader.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(254, 255, 250));
        lblHeader.setText("Bảng thông tin");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        lblMaNhanVien.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMaNhanVien.setForeground(new java.awt.Color(3, 100, 117));
        lblMaNhanVien.setText("Mã nhân viên");

        cbxMaNhanVien.setBackground(new java.awt.Color(107, 195, 196));
        cbxMaNhanVien.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxMaNhanVien.setForeground(new java.awt.Color(3, 100, 117));
        cbxMaNhanVien.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));

        lblHoTen.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(3, 100, 117));
        lblHoTen.setText("Họ và tên");

        txtHoTen.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtHoTen.setForeground(new java.awt.Color(3, 100, 117));
        txtHoTen.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtHoTen.setEnabled(false);
        txtHoTen.setMinimumSize(new java.awt.Dimension(3, 26));
        txtHoTen.setPreferredSize(new java.awt.Dimension(3, 26));

        lblGioiTinh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(3, 100, 117));
        lblGioiTinh.setText("Giới tính");

        txtGioiTinh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtGioiTinh.setForeground(new java.awt.Color(3, 100, 117));
        txtGioiTinh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtGioiTinh.setEnabled(false);
        txtGioiTinh.setMinimumSize(new java.awt.Dimension(3, 26));
        txtGioiTinh.setPreferredSize(new java.awt.Dimension(3, 26));

        lblNgaySinh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(3, 100, 117));
        lblNgaySinh.setText("Ngày Sinh*");

        txtNgaySinh.setForeground(new java.awt.Color(3, 100, 117));
        txtNgaySinh.setDate(new java.util.Date(1561799207000L));
        txtNgaySinh.setDateFormatString("yyyy-MM-dd");
        txtNgaySinh.setEnabled(false);
        txtNgaySinh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        lblNoiSinh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNoiSinh.setForeground(new java.awt.Color(3, 100, 117));
        lblNoiSinh.setText("Nơi sinh*");

        txtNoiSinh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNoiSinh.setForeground(new java.awt.Color(3, 100, 117));
        txtNoiSinh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtNoiSinh.setEnabled(false);
        txtNoiSinh.setMinimumSize(new java.awt.Dimension(3, 26));
        txtNoiSinh.setPreferredSize(new java.awt.Dimension(3, 26));

        lblSoDienThoai.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblSoDienThoai.setForeground(new java.awt.Color(3, 100, 117));
        lblSoDienThoai.setText("Số điện thoại*");

        txtSoDienThoai.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtSoDienThoai.setForeground(new java.awt.Color(3, 100, 117));
        txtSoDienThoai.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtSoDienThoai.setEnabled(false);
        txtSoDienThoai.setMinimumSize(new java.awt.Dimension(3, 26));
        txtSoDienThoai.setPreferredSize(new java.awt.Dimension(3, 26));
        txtSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyPressed(evt);
            }
        });

        lblDanToc.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblDanToc.setForeground(new java.awt.Color(3, 100, 117));
        lblDanToc.setText("Dân tộc*");

        txtDanToc.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtDanToc.setForeground(new java.awt.Color(3, 100, 117));
        txtDanToc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtDanToc.setEnabled(false);
        txtDanToc.setMinimumSize(new java.awt.Dimension(3, 26));
        txtDanToc.setPreferredSize(new java.awt.Dimension(3, 26));

        lblTonGiao.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTonGiao.setForeground(new java.awt.Color(3, 100, 117));
        lblTonGiao.setText("Tôn giáo*");

        txtTonGiao.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtTonGiao.setForeground(new java.awt.Color(3, 100, 117));
        txtTonGiao.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtTonGiao.setEnabled(false);
        txtTonGiao.setMinimumSize(new java.awt.Dimension(3, 26));
        txtTonGiao.setPreferredSize(new java.awt.Dimension(3, 26));

        lblQuocTich.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblQuocTich.setForeground(new java.awt.Color(3, 100, 117));
        lblQuocTich.setText("Quốc tịch*");

        txtQuocTich.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtQuocTich.setForeground(new java.awt.Color(3, 100, 117));
        txtQuocTich.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtQuocTich.setEnabled(false);
        txtQuocTich.setMinimumSize(new java.awt.Dimension(3, 26));
        txtQuocTich.setPreferredSize(new java.awt.Dimension(3, 26));

        lblDiaChiThuongTru.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblDiaChiThuongTru.setForeground(new java.awt.Color(3, 100, 117));
        lblDiaChiThuongTru.setText("Địa chỉ thường trú*");

        txtDiaChiThuongTru.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtDiaChiThuongTru.setForeground(new java.awt.Color(3, 100, 117));
        txtDiaChiThuongTru.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtDiaChiThuongTru.setEnabled(false);
        txtDiaChiThuongTru.setMinimumSize(new java.awt.Dimension(3, 26));
        txtDiaChiThuongTru.setPreferredSize(new java.awt.Dimension(3, 26));

        lblDiaChiTamTru.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblDiaChiTamTru.setForeground(new java.awt.Color(3, 100, 117));
        lblDiaChiTamTru.setText("Địa chỉ tạm trú*");

        txtDiaChiTamTru.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtDiaChiTamTru.setForeground(new java.awt.Color(3, 100, 117));
        txtDiaChiTamTru.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtDiaChiTamTru.setEnabled(false);
        txtDiaChiTamTru.setMinimumSize(new java.awt.Dimension(3, 26));
        txtDiaChiTamTru.setPreferredSize(new java.awt.Dimension(3, 26));

        lblNguyenQuan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNguyenQuan.setForeground(new java.awt.Color(3, 100, 117));
        lblNguyenQuan.setText("Nguyên quán*");

        txtNguyenQuan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNguyenQuan.setForeground(new java.awt.Color(3, 100, 117));
        txtNguyenQuan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtNguyenQuan.setEnabled(false);
        txtNguyenQuan.setMinimumSize(new java.awt.Dimension(3, 26));
        txtNguyenQuan.setPreferredSize(new java.awt.Dimension(3, 26));

        lblGhiChu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(3, 100, 117));
        lblGhiChu.setText("Ghi chú");

        txtGhiChu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(3, 100, 117));
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(3, 100, 117)));
        txtGhiChu.setEnabled(false);
        txtGhiChu.setMinimumSize(new java.awt.Dimension(3, 26));
        txtGhiChu.setPreferredSize(new java.awt.Dimension(3, 26));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNhanVien)
                            .addComponent(lblHoTen)
                            .addComponent(lblNoiSinh)
                            .addComponent(lblGioiTinh))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(txtNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(lblDiaChiThuongTru)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiaChiThuongTru, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNguyenQuan, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(57, 57, 57))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(lblDiaChiTamTru)
                                        .addGap(43, 43, 43)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiaChiTamTru, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNguyenQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblSoDienThoai)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblGhiChu)
                        .addGap(104, 104, 104)
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblQuocTich)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblTonGiao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblDanToc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNhanVien)
                    .addComponent(txtDiaChiThuongTru, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaChiThuongTru)
                    .addComponent(cbxMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDanToc)
                    .addComponent(txtDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTonGiao)
                                .addComponent(txtTonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHoTen)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblQuocTich)
                                    .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(lblGhiChu)
                                .addGap(42, 42, 42)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGioiTinh)
                                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDiaChiTamTru, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiaChiTamTru))
                                .addGap(25, 25, 25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNoiSinh)
                                .addComponent(txtNoiSinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNguyenQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNguyenQuan))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoDienThoai)
                            .addComponent(lblNgaySinh))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(254, 255, 250));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(107, 195, 196)));

        jPanel8.setBackground(new java.awt.Color(3, 100, 117));

        lblHeader1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(254, 255, 250));
        lblHeader1.setText("Chức năng");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblHeader1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        btnThem.setBackground(new java.awt.Color(3, 100, 117));
        btnThem.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(107, 195, 196));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlnstl/src/add-group.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.setEnabled(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(3, 100, 117));
        btnSua.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(107, 195, 196));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlnstl/src/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.setEnabled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(3, 100, 117));
        btnXoa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(107, 195, 196));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlnstl/src/remove-user.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.setBorder(null);
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setBackground(new java.awt.Color(3, 100, 117));
        btnMoi.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(107, 195, 196));
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlnstl/src/add-group.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.setBorder(null);
        btnMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable2.setBackground(new java.awt.Color(254, 255, 250));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(3, 100, 117));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ và tên", "Giới tính", "Ngày Sinh", "Nơi sinh", "Nguyên quán", "Địa chỉ thường trú", "Địa chỉ tạm trú", "Số điện thoại", "Dân tộc", "Tôn giáo", "Quốc tịch", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(3, 100, 117));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoDienThoaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) txtSoDienThoai.setEditable(false);
        else txtSoDienThoai.setEditable(true);
    }//GEN-LAST:event_txtSoDienThoaiKeyPressed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtHoTen.getText().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Họ tên không được để trống");
        } else if (txtGioiTinh.getText().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Giới tính không được để trống");
        } else if (txtNoiSinh.getText().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Nơi sinh không được để trống");
        } else if (txtDiaChiThuongTru.getText().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Địa chỉ thường trú không được để trống");
        } else if (txtSoDienThoai.getText().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Số điện thoại không được để trống");
        } else if (txtDiaChiTamTru.getText().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Địa chỉ tạm trú không được để trống");
        } else if (txtNguyenQuan.getText().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Nguyên Quán không được để trống");
        } else if (txtQuocTich.getText().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Quốc tịch không được để trống");
        } else if (txtTonGiao.getText().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Tôn giáo không được để trống");
        } else if (txtDanToc.getText().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Dân tộc không được để trống");
        } else {
        String NgaySinh = dateFormat.format(txtNgaySinh.getDate());
        ThongTinCaNhanBUS.Them(cbxMaNhanVien.getSelectedItem().toString(), txtHoTen.getText(), txtGioiTinh.getText(), NgaySinh,txtNoiSinh.getText(),
                txtNguyenQuan.getText(), txtDiaChiThuongTru.getText(), txtDiaChiTamTru.getText(), txtSoDienThoai.getText(),
                txtDanToc.getText(), txtTonGiao.getText(), txtQuocTich.getText(),  
                txtGhiChu.getText());
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        showTTCN();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String NgaySinh = dateFormat.format(txtNgaySinh.getDate());
        ThongTinCaNhanBUS.Sua(txtHoTen.getText(), txtGioiTinh.getText(), NgaySinh, txtNoiSinh.getText(),txtNguyenQuan.getText(), txtDiaChiThuongTru.getText(), txtDiaChiTamTru.getText(), txtSoDienThoai.getText(),
                txtDanToc.getText(), txtTonGiao.getText(), txtQuocTich.getText(), txtGhiChu.getText(), cbxMaNhanVien.getSelectedItem().toString());
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        showTTCN();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        ThongTinCaNhanBUS.Xoa(cbxMaNhanVien.getSelectedItem().toString());
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        showTTCN();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
                                             
            // TODO add your handling code here:
//            cbxMaNhanVien.removeAllItems();
//            ThongTinCaNhanBUS.getCBbox(cbxMaNhanVien);
            
            txtHoTen.setEnabled(true);
            txtGioiTinh.setEnabled(true);
            txtNgaySinh.setEnabled(true);
            txtNoiSinh.setEnabled(true);
            txtNguyenQuan.setEnabled(true);
            txtDiaChiThuongTru.setEnabled(true);
            txtDiaChiTamTru.setEnabled(true);
            txtSoDienThoai.setEnabled(true);
            txtDanToc.setEnabled(true);
            txtTonGiao.setEnabled(true);
            txtQuocTich.setEnabled(true);
            txtGhiChu.setEnabled(true);
            btnThem.setEnabled(true);
            btnXoa.setEnabled(false);
            btnSua.setEnabled(false);
            
            txtDanToc.setText("");
            txtDiaChiTamTru.setText("");
            txtDiaChiThuongTru.setText("");
            txtGhiChu.setText("");
            txtNguyenQuan.setText("");
            txtQuocTich.setText("");
            txtTonGiao.setText("");
            txtSoDienThoai.setText("");
            txtNoiSinh.setText("");

            String maNV= cbxMaNhanVien.getSelectedItem().toString();
            Connection connect = KetNoiSQL.layKetnoi();
            String sql ="SELECT HoTen,GioiTinh,NgaySinh FROM dbo.TblTTNVCoBan WHERE MANV='"+maNV+"'";
            try {
                Statement statement = connect.createStatement();
                ResultSet rs = statement.executeQuery(sql);
                if (rs.next()){
                    txtHoTen.setText(rs.getString("HoTen"));
                    txtGioiTinh.setText(rs.getString("GioiTinh"));
                    txtNgaySinh.setDate(rs.getDate("NgaySinh"));

                }
                rs.close();
                statement.close();
                connect.close();

            } catch (SQLException ex) {
                System.out.println("LOI KHONG TRUY XUAT DUOC. KHONG LAY DUOC DU LIEU LOGIN");
            }
    }//GEN-LAST:event_btnMoiActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        cbxMaNhanVien.removeAllItems();
        ThongTinCaNhanDAL.getCBboxTb(cbxMaNhanVien);
        
        txtHoTen.setEnabled(true);
        txtGioiTinh.setEnabled(true);
        txtNgaySinh.setEnabled(true);
        txtNoiSinh.setEnabled(true);
        txtNguyenQuan.setEnabled(true);
        txtDiaChiThuongTru.setEnabled(true);
        txtDiaChiTamTru.setEnabled(true);
        txtSoDienThoai.setEnabled(true);
        txtDanToc.setEnabled(true);
        txtTonGiao.setEnabled(true);
        txtQuocTich.setEnabled(true);
        txtGhiChu.setEnabled(true);
        btnThem.setEnabled(true);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
        
        int i = jTable2.getSelectedRow();
        cbxMaNhanVien.setSelectedItem(model.getValueAt(i, 0).toString());
        txtHoTen.setText(model.getValueAt(i, 1).toString());
        txtGioiTinh.setText(model.getValueAt(i, 2).toString());
        txtNoiSinh.setText(model.getValueAt(i, 4).toString());
        txtNguyenQuan.setText(model.getValueAt(i, 5).toString());
        txtDiaChiThuongTru.setText(model.getValueAt(i, 6).toString());
        txtDiaChiTamTru.setText(model.getValueAt(i, 7).toString());
        txtSoDienThoai.setText(model.getValueAt(i, 8).toString());
        txtDanToc.setText(model.getValueAt(i, 9).toString());
        txtTonGiao.setText(model.getValueAt(i, 10).toString());
        txtQuocTich.setText(model.getValueAt(i, 11).toString());
        txtGhiChu.setText(model.getValueAt(i, 12).toString());
        try {
            int srow = jTable2.getSelectedRow();
            Date NgaySinh = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(srow, 3));
            txtNgaySinh.setDate(NgaySinh);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxMaNhanVien;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblDanToc;
    private javax.swing.JLabel lblDiaChiTamTru;
    private javax.swing.JLabel lblDiaChiThuongTru;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNguyenQuan;
    private javax.swing.JLabel lblNoiSinh;
    private javax.swing.JLabel lblQuocTich;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTonGiao;
    private javax.swing.JTextField txtDanToc;
    private javax.swing.JTextField txtDiaChiTamTru;
    private javax.swing.JTextField txtDiaChiThuongTru;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHoTen;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private javax.swing.JTextField txtNguyenQuan;
    private javax.swing.JTextField txtNoiSinh;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTonGiao;
    // End of variables declaration//GEN-END:variables
}
